In [61]:
# Dependency imports
!pip install torch
import torch
from importlib import reload

# Local imports
from utils import *
import dataclass
reload(dataclass)

<module 'dataclass' from 'c:\\Users\\Ramkumare\\Documents\\personal_work\\transforms_ml\\dataclass.py'>

In [62]:
DATA = r".\introduction_data.txt"
TRANING_DATA_PERCENTAGE = 90
BATCH_SIZE = 4  # how many independent seq will we process in parellel
# Note : We dont actually train of model with all the data at once we only train our dataset with chunk of the sample ooof data at once
# Because traing the dataset with all data at once will be conputatially heavy.
# So our chunk sample  will have max size to be smapled and trained by the model. which is called blocked size
BLOCK_SIZE = 10

In [63]:
data = read_data(DATA)
print("length of the data set : ", len(data))

length of the data set :  198


In [64]:
unique_char_list = get_unique_chars(data)
vocab_size = len(unique_char_list)
print("All unique chars in the data : {}".format("".join(unique_char_list)))
print("Total possibily char we get : {}".format(vocab_size))

All unique chars in the data : 
 .HIabcdefhiklmnoprstuvwy
Total possibily char we get : 26


In [65]:
# What is tokenzie?
# Converting seq of text to seq of intergen with some seq of vocalbulary

# Note need to learn about "SentencePiece" tokenzier used by google
# Note need to learn about "tiktoken" tokenzier used by OpenAI
encode_mapper_dict = str_to_int(unique_char_list)
decode_mapper_dict = int_to_str(unique_char_list)

In [66]:
# torch.tensor is a multi-dimensioanl matrix containing elemenst of same type
tokenize_data = torch.tensor(encode(data, encode_mapper_dict), dtype=torch.long)
print(tokenize_data)

tensor([ 3, 12,  1, 15, 25,  1, 16,  5, 15,  9,  1, 12, 20,  1, 19,  5, 15, 13,
        22, 15,  5, 19,  9,  1, 12,  1,  5, 15,  1, 18, 12, 18,  9, 14, 12, 16,
         9,  1,  8,  9, 23,  9, 14, 17, 18,  9, 19,  0,  4,  1, 11, 17, 18,  9,
         1, 25, 17, 22,  1, 24, 12, 14, 14,  1,  6,  9,  1, 22, 20,  9, 10, 22,
        14,  1, 10, 17, 19,  1, 17, 21, 11,  9, 19, 20,  1, 21, 17,  1, 15,  5,
        13,  9,  1, 21, 11,  9, 12, 19,  1, 14, 12, 10,  9, 20,  1,  6,  9, 21,
        21,  9, 19,  2,  0,  3, 22, 15,  5, 16, 20,  1,  5, 19,  9,  1, 11,  5,
        19,  8,  1, 21, 17,  1, 22, 16,  8,  9, 19, 20, 21,  5, 16,  8,  1,  5,
        16,  8,  1, 20,  9, 14, 10, 12, 20, 11,  1,  6, 22, 21,  1, 23,  9, 19,
        25,  1, 13, 12, 16,  8,  1, 11,  9,  5, 19, 21,  9,  8,  1, 20, 18,  9,
         7, 12,  9, 20,  1, 12, 16,  1, 21, 11,  9,  1, 24, 17, 19, 14,  8,  2])


In [67]:
# split dataset for traning and test data
traning_data_end_index = int(TRANING_DATA_PERCENTAGE * len(tokenize_data))
train_data = tokenize_data[:traning_data_end_index]
test_data = tokenize_data[traning_data_end_index:]

In [68]:
data = dataclass.TextData(train_data, test_data, BLOCK_SIZE, BATCH_SIZE)
data.get_context_target()

tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([3]) and the target : 12
tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([ 3, 12]) and the target : 1
tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([ 3, 12,  1]) and the target : 15
tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([ 3, 12,  1, 15]) and the target : 25
tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([ 3, 12,  1, 15, 25]) and the target : 1
tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([ 3, 12,  1, 15, 25,  1]) and the target : 16
tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([ 3, 12,  1, 15, 25,  1, 16]) and the target : 5
tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([ 3, 12,  1, 15, 25,  1, 16,  5]) and the target : 15
tensor([12,  1, 15, 25,  1, 16,  5, 15,  9,  1])
The context is tensor([ 3, 12,  1, 15, 25,  1, 16,  5, 15]) and the

In [69]:
torch.manual_seed(1337)